### ISSUE TITLE
Watcher stops before doing any changes

### ISSUE THREAD

**Issue by venelinn** [berstend/gulp-sass-inheritance#8]
Hi,
I've issue with the watcher.
SO, when I run the watcher.. I'm getting this without doing anything..
I'm using the example from you website.
Is it normal?

```
[15:43:09] Starting 'setWatch'...
[15:43:09] Finished 'setWatch' after 109 μs
[15:43:09] Starting 'sass'...
[15:43:17] Finished 'sass' after 8.82 s
[15:43:17] Starting 'watch'...
[15:43:17] Finished 'watch' after 17 μs
```

**Comment by salex772** [comment]
Looks weird. By the way, because of disfunction of this plugin I was compelled to switch to stylus. It works pretty fast.

**Comment by berstend** [comment]
The new [v1.1.0](https://github.com/berstend/gulp-sass-inheritance#v110-2017-05-13) release fixes all outstanding issues, let me know if you still experience issues. :-)

**Comment by BirkAndMe** [comment]
I know this is closed, but I had the same issue. The thing was I didn't add any watch functions inside the `watch` task.

Maybe update the documentation with an example function, so gulp newbies (like me) get a better start:
```
gulp.task('watch', ['setWatch', 'sass'], function() {
    //your watch functions...
    //gulp.watch('src/styles/**/*.scss', ['sass']);
});
```
